rootLogger = ERROR, STDOUT
loggers = com.ap4.server
logger.com.ap4.server.name = com.ap4.server
logger.com.ap4.server.level = DEBUG
appender.console.name = STDOUT
appender.console.type = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = {%-5level} %d{yyyy-MM-dd HH:mm:SSS} {%t} %c{1} - %msg%n 